Week three step five tutorial
panerorenn9541/step pull request #10
Opened 2020-07-01 17:57 UTC by panerorenn9541

Finish up to step five of the week three tutorial.

2020-07-06 19:16 UTC, huzcn commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    return json;
To improve readability, it's better to organize your code to align public methods together, and private methods together.

2020-07-06 19:17 UTC, huzcn commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  }
To improve readability, it's better to organize your code to align public methods together, and private methods together.

2020-07-06 19:18 UTC, huzcn commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  private String getParameter(HttpServletRequest request, String name, String defaultValue) {
Maybe rename this to getRequestParameterOrDefault to be clearer?

2020-07-06 19:24 UTC, huzcn commented on portfolio/src/main/java/com/google/sps/data/Comment.java
> +}
Why do you put this class in a separate file? If it's only in DataServlet.java, it's better to be created there. Besides, if this comment is only a string literal, there is no need to define this class.

2020-07-06 19:26 UTC, huzcn approved these changes
Leave a few comments primarily in java code.

2020-07-06 19:27 UTC, huzcn requested changes
changes needed before merging

2020-07-07 22:36 UTC, panerorenn9541 commented
Fix please take a look

2020-07-08 00:32 UTC, panerorenn9541 commented
Fix and commit changes

2020-07-08 17:06 UTC, huzcn approved these changes
Nice!

2020-07-08 18:18 UTC, merged